import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { 
	MdcTypographyModule,
	MdcRippleModule,
	MdcElevationModule,
	MdcButtonModule,
	MdcFabModule,
	MdcIconToggleModule,
	MdcFormFieldModule, 
	MdcCheckboxModule,
	MdcRadioModule,
	MdcSelectModule,
	MdcSliderModule,
	MdcSwitchModule,
	MdcTextFieldModule,
	MdcAppBarModule,
	MdcCardModule,
	MdcChipsModule,
	MdcDialogModule,
	MdcDrawerModule,
	MdcIconModule,
	MdcLinearProgressModule,
	MdcListModule,
	MdcMenuModule,
	MdcTabModule,
	MdcSnackbarModule
} from '@angular-mdc/web'

@NgModule({
  imports: [
    CommonModule,
    MdcTypographyModule,
	MdcRippleModule,
	MdcElevationModule,
	MdcButtonModule,
	MdcFabModule,
	MdcIconToggleModule,
	MdcFormFieldModule, 
	MdcCheckboxModule,
	MdcRadioModule,
	MdcSelectModule,
	MdcSliderModule,
	MdcSwitchModule,
	MdcTextFieldModule,
	MdcAppBarModule,
	MdcCardModule,
	MdcChipsModule,
	MdcDialogModule,
	MdcDrawerModule,
	MdcIconModule,
	MdcLinearProgressModule,
	MdcListModule,
	MdcMenuModule,
	MdcTabModule,
	MdcSnackbarModule
  ],
  exports: [
  	MdcTypographyModule,
	MdcRippleModule,
	MdcElevationModule,
	MdcButtonModule,
	MdcFabModule,
	MdcIconToggleModule,
	MdcFormFieldModule, 
	MdcCheckboxModule,
	MdcRadioModule,
	MdcSelectModule,
	MdcSliderModule,
	MdcSwitchModule,
	MdcTextFieldModule,
	MdcAppBarModule,
	MdcCardModule,
	MdcChipsModule,
	MdcDialogModule,
	MdcDrawerModule,
	MdcIconModule,
	MdcLinearProgressModule,
	MdcListModule,
	MdcMenuModule,
	MdcTabModule,
	MdcSnackbarModule
  ],
  declarations: []
})
export class MdcModule { }
